language: python
python:
  - "3.8"
services:
  - docker

install:
  - pip install "poetry<2"
  - poetry install
before_script:
  - python --version
  - poetry --version
  - docker version
script:
  - make test
after_failure:
  - ./inspect_fixtures.sh
after_success:
  - |
    if [[ "$TRAVIS_REPO_SLUG" == "lavie/runlike" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      echo "$DOCKERHUB_PASSWORD" | docker login -u assaflavie --password-stdin
      make pypi push
    fi
