#!/usr/bin/env python3

import importlib.util
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _load_module(script_path, module_name):
    spec = importlib.util.spec_from_file_location(module_name, str(script_path))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _json_dump(payload):
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def build_expected_probe_results(probe_results, probes, root=ROOT):
    probe_module = _load_module(
        Path(root) / "tools" / "run_probes.py",
        "run_probes")
    expected = dict(probe_results)
    expected["probe_definitions"] = probe_module.build_probe_results_metadata(
        probes,
        root=root)
    return expected


def missing_probe_results_check(root):
    root = Path(root)
    return {
        "expected": "Generated by `make generate-probe-results`.\n",
        "path": root / "generated" / "probe-results.json",
    }


def build_checks(root=ROOT):
    root = Path(root)
    probe_results_path = root / "generated" / "probe-results.json"
    if not probe_results_path.exists():
        return [missing_probe_results_check(root)]

    ledger_module = _load_module(
        root / "tools" / "build_probe_work_ledger.py",
        "build_probe_work_ledger")
    matrix_module = _load_module(
        root / "tools" / "build_support_matrix.py",
        "build_support_matrix")

    dictionary_entries = ledger_module.load_dictionary_entries(
        root / "spec" / "option-dictionary")
    probes = ledger_module.load_probe_definitions([
        root / "tests" / "probes",
    ])
    probe_results = ledger_module.load_probe_results(probe_results_path)
    ledger = ledger_module.build_probe_work_ledger(
        dictionary_entries,
        probes,
        probe_results)

    matrix_dictionary_entries = matrix_module.load_dictionary_entries(
        root / "spec" / "option-dictionary")
    matrix_probes = matrix_module.load_probe_definitions([
        root / "tests" / "probes",
    ])
    matrix_probe_results = matrix_module.load_probe_results(probe_results_path)
    matrix = matrix_module.build_support_matrix(
        matrix_dictionary_entries,
        matrix_probes,
        matrix_probe_results,
        target=matrix_module.load_target(root / "spec" / "current-target.json"))

    return [
        {
            "expected": _json_dump(build_expected_probe_results(
                matrix_probe_results,
                matrix_probes,
                root)),
            "path": root / "generated" / "probe-results.json",
        },
        {
            "expected": _json_dump(ledger),
            "path": root / "generated" / "probe-work-ledger.json",
        },
        {
            "expected": _json_dump(matrix),
            "path": root / "generated" / "support-matrix.json",
        },
        {
            "expected": matrix_module.render_support_matrix_markdown(matrix),
            "path": root / "generated" / "support-matrix.md",
        },
    ]


def find_stale_files(checks):
    stale = []
    for check in checks:
        path = Path(check["path"])
        if not path.exists() or path.read_text() != check["expected"]:
            stale.append(str(path))
    return stale


def report_stale_files(stale):
    print("Generated files are stale:", file=sys.stderr)
    for path in stale:
        print("  %s" % path, file=sys.stderr)
    print(
        "Run `make refresh-support-artifacts` "
        "after updating generated inputs.",
        file=sys.stderr)
    return 1


def main(argv=None):
    stale = find_stale_files(build_checks(ROOT))
    if stale:
        return report_stale_files(stale)
    print("Generated files are current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
